### ISSUE TITLE
Forward geo error: invalid type: sequence, expected a string

### ISSUE THREAD

**Issue by ghost** [georust/rust-geocoding#54]
use geocoding::{Opencage, Forward, Point};   - using version 0.3.1 in cargo.toml

let oc: Opencage = Opencage::new("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx".to_string());
let address = "Schwabing, München";
**let res: Vec<Point<f64>> = oc.forward(&address).unwrap();**
let first_result = &res[0];

The third line above responds with the error below:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Json(Error("invalid type: sequence, expected a string", line: 1, column: 393)), url: None }', src/main.rs:91:53

Could it be due to a change in API with OpenCage? I tried OpenStreetMap too, which also responds with a type error. 3rd option not workable as it's limited to Switzerland vs being worldwide.

Use case is to get long lat by address (city, state, zip, country).

**Comment by freyfogle** [comment]
Hi,

Ed from OpenCage here. 

Can you establish at all what is causing the error, I mean which part of the response it is dying on?

The most recent change was over a month ago (see [Change Log](https://github.com/OpenCageData/opencagedata-misc-docs/blob/master/CHANGES.md)), which I suppose this could be related to.

Basically in the `components` portion of the response there can now be a key `ISO_3166-2` which is a list of ISO 3166-2 codes for the location. Here is a [detailed blog post describing the addition to the API](https://blog.opencagedata.com/post/now-with-iso-3166-2-codes).

I hope that helps.

**Comment by freyfogle** [comment]
sorry, I guess I am not formulating my question clearly. Yes, I see the error message, it was posted in the initial message in this thread. My question is which part of the JSON is causing this errror in the decoding? Which content is at "column 392"?
Please bear in mind I know nothing about Rust and am not the maintainer of this module. 

Our API is returning:

```
     ...
      "components": {
        "ISO_3166-1_alpha-2": "DE",
        "ISO_3166-1_alpha-3": "DEU",
        "ISO_3166-2": [
          "DE-BY"
        ],
        "_category": "place",
        "_type": "neighbourhood",
        "city": "München",
        "city_district": "Schwabing-Freimann",
        "continent": "Europe",
        "country": "Deutschland",
        "country_code": "de",
        "political_union": "European Union",
        "postcode": "80805",
        "state": "Bayern",
        "state_code": "BY",
        "suburb": "Schwabing"
      },
```

my guess is it is the newly-added `ISO_3166-2` that is causing problems as Rust is expecting the value to be a string, not a list. Please see the blog post to understand why it needs to be a list (in short: many countries have multiple ISO 3166-2 codes).

**Comment by b4l** [comment]
@freyfogle this seems to be the issue indeed as components is defined as a `HashMap<String, String>`.

**Comment by b4l** [comment]
Probably can test this by replacing the String value with something like `HashMap<String, Component>`
```rust
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Component {
    String(String),
    List(Vec<String>),
}
```

**Comment by freyfogle** [comment]
> Hi Ed, I'm not feeding or getting any json.
> 

yes, you are getting back JSON when you query our API

Please see pur demo page: https://opencagedata.com/demo
Put in the query "Schwabing, München" and you can see exactly the JSON we are returning.


<img width="1203" alt="Bildschirmfoto 2022-06-25 um 13 08 18" src="https://user-images.githubusercontent.com/351074/175770922-5ffc6ff3-d860-4621-b811-8b3dac627468.png">

**Comment by urschrei** [comment]
> or `HashMap<String, serde_json::Value>`

That seems to work. @b4l would you like to push a PR with the fix?

**Comment by b4l** [comment]
@urschrei yes, I can do that.

**Comment by urschrei** [comment]
v0.4.0 is on crates.io, with the fix. Thanks @freyfogle and @b4l for the diagnosis and PR

**Comment by urschrei** [comment]
That error doesn't originate in `geocoding` I'm afraid.

**Comment by b4l** [comment]
@AppyCat this seems to be expected, resulting from how the blocking `reqwest` Client interacts with the tokio runtime: https://github.com/seanmonstar/reqwest/issues/1017

**Comment by freyfogle** [comment]
Hi yes, there are many differences between OpenStreetMap and OpenCage.
I dont think the rust SDK is really the place for the discussion

Spend some time reading [the OpenCage geocoding API docs](https://opencagedata.com/api).
